[common]
# 本专服 id
# id = 1
# 本专服名称
# name = "local-dev"
# 本专服登录秘钥
# secret = "p5KJRYz777mBd559"
# 本专服充值秘钥
# paymentsecret = "pUawkHg1EWxprV8h"
# 本专服充值透传参数秘钥
# paymentpayloadsecretkey = "uWAGGdu2bhqsEocu"
# 是否开发模式
# isdevelop = true

# etcd 地址
etcdaddress = ":12379;:22329;:32329"
# etcdaddress = "etcd1:2379;etcd2:2379;etcd3:2379"
# etcd 前缀
etcdprefix = "node"
# rpc 心跳间隔，秒
rpcheart = 10


[room]
[room-1]
# 区服编号 1000~1999, gould=2
id = 1000
# 名称
name = "room-1"
# 版本号
version = 0
# 性能监控地址
pprofaddr = ":7081"

[room-2]
# 区服编号 1000~1999
id = 1001
# 名称
name = "room-2"
# 版本号
version = 0
# 性能监控地址
pprofaddr = ":7082"