[common]
# 本专服 id
# id = 1
# 本专服名称
# name = "local-dev"
# 本专服登录秘钥
# secret = "p5KJRYz777mBd559"
# 本专服充值秘钥
# paymentsecret = "pUawkHg1EWxprV8h"
# 本专服充值透传参数秘钥
# paymentpayloadsecretkey = "uWAGGdu2bhqsEocu"
# 是否开发模式
# isdevelop = true

# etcd 地址
etcdaddress = "etcd1:2379;etcd2:2379;etcd3:2379"
# etcd 前缀
etcdprefix = "node"
# rpc 心跳间隔，秒
rpcheart = 10


[room]
[room-1]
# 区服编号
id = 10
# 名称
name = "room-1"
# 版本号
version = 0
# 性能监控地址
pprofaddr = ":7081"

[room-2]
# 区服编号
id = 11
# 名称
name = "room-2"
# 版本号
version = 0
# 性能监控地址
pprofaddr = ":7082"